apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nginx-test
    name: debian
  spec:
    dockerImageRepository: debian
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nginx-test
    name: nginx-test
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nginx-test
    name: nginx-test
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nginx-test:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/git001/nginx-osev3.git
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: debian:jessie
      type: Docker
    triggers:
    - github:
        secret: NAYWj7reurv5q2EVBEyU
      type: GitHub
    - generic:
        secret: USpK2sGw0tgxI08WFycA
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nginx-test
    name: nginx-test
  spec:
    replicas: 1
    selector:
      app: nginx-test
      deploymentconfig: nginx-test
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nginx-test
          deploymentconfig: nginx-test
      spec:
        containers:
        - name: ng-socklog
          image: nginx-test:latest
          command:
           - /usr/sbin/socklog
           - inet
           - "0"
           - "8514"
          ports:
          - containerPort: 8514
            protocol: UDP
        - name: nginx-test
          image: nginx-test:latest
          command:
           - /nginx-wrapper.sh
          env:
          - name: WORKER_PROCESSES
            value: "2"
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nginx-test
        - ng-socklog
        from:
          kind: ImageStreamTag
          name: nginx-test:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nginx-test
    name: nginx-test
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8514-tcp
      port: 8514
      protocol: UDP
      targetPort: 8514
    selector:
      app: nginx-test
      deploymentconfig: nginx-test
  status:
    loadBalancer: {}
kind: List
metadata: {}
